### ISSUE TITLE
Timesheet - Access Denied - Old Timesheets

### ISSUE THREAD

**Issue by sbcDeveloper** [sbcDeveloper/bugs-in-time#1]
when attempting to access a timesheet for the PayPeriod of 2015-02 or older, the user (eeid 16294) is denied - "Access denied. You are not authorized to access this page".  Note, no issues accessing timesheets in post 2015-02 pay periods.

**Comment by sbcTestor001** [comment]
This is a test comment on this first issue

**Comment by sbcDeveloper** [comment]
note this is an ee with two Jobs.

**Comment by struven** [comment]
EE 16294 was not an employee in 201502, hence the Access Denied message, which is generated in TimeSheetControl.ascx.cs.ValidateURL from DBAccess.IsEmployeeIDVlaid(payPeriod, employeeID). Ideally we should populate the PayPeriod ddl with payperiods subsequent to when the user became an emloyee.

**Comment by struven** [comment]
Oops., didn't mean to close the issue.

**Comment by sbcTestor001** [comment]
should the suggested change (populate the pay period ddl with only pay periods relevant to the employee id) be a fix for this version, or an enhancement in the next version?  - nt

**Comment by struven** [comment]
This should not be difficult so we can include it; I will write an sp to call from TimeSheetMain.aspx.cs.PageLoad that inclued EmployeeID as a parameter to  retrieve only relevant payperiods; I'm thinking to inlcude only Payperiods that have a timesheet in ESSPlus.Timesheets based on employeeid and job.

**Comment by sbcTestor001** [comment]
The current SP called from TimeSheetMain.aspx.cs is GetESSPayPeriods("%", "Y")

**Comment by struven** [comment]
That's right, I don't want to modify it to accomodate this because it is used in so many places and I might break one of those; so I'll just build a new one.

**Comment by struven** [comment]
Modified Timesheet main and DBAccess to call a new sp GetEIDPayperiods; tested, rolled to subversion for NT to test. Needs to go to qual.
