### ISSUE TITLE
Question:  Eliminate Redundant label?

### ISSUE THREAD

**Issue by sbcTestor001** [sbcDeveloper/bugs-in-time#21]
Can this redundant information be removed? (not referring to the signed in label, but the other one "Reviewer:.."
![redundantlabel_a](https://cloud.githubusercontent.com/assets/13141754/8788269/024887c0-2eee-11e5-84da-b2d23b9a5e73.jpg)

**Comment by struven** [comment]
I see no reason to display the Reviewer on the Review... tab; hopefully, the Reviewer knows their own name, and if it is a developer impersonating someone, then they should know who they are impersonating. So, yes, eliminate it.

**Comment by sbcTestor001** [comment]
applies to both submit and approve pages.  local edit completed.
