### ISSUE TITLE
PayPeriod DDL's "Open" Value Displays Wrong Period Ending Date

### ISSUE THREAD

**Issue by sbcTestor001** [sbcDeveloper/bugs-in-time#22]
Today if the first day of the 201516 pay period but the 201515 pay period is still open.  Selecting the open pay period results in the 201516 period ending date displaying, not the 201515 period ending date displaying.
![openpayperiodhaswrongendingdate](https://cloud.githubusercontent.com/assets/13141754/8788916/d8996dcc-2ef2-11e5-84c9-71136aa02c31.png)

**Comment by struven** [comment]
Both payperiods are open at this time because we are working on both. "Open" should not be an option in the ddl, only specific payperiods.

**Comment by sbcTestor001** [comment]
the problem is in the u control

**Comment by sbcTestor001** [comment]
removed "Open" pay period option from the u control DDL and assigned index 0 as default
