### ISSUE TITLE
Timesheet - Formatting - Too Many Hours

### ISSUE THREAD

**Issue by sbcTestor001** [sbcDeveloper/bugs-in-time#23]
after entering in too many hours into a cell, clicking "OK" on the pop up, a single 0 without std formatting is automatically entered into the cell.  after tabbing out of the cell, the cell remains unchanged. 
![toomanyhrs_a](https://cloud.githubusercontent.com/assets/13141754/8801955/f7adec1c-2f72-11e5-91ab-9a4a3a08bc0c.jpg)

**Comment by sbcDeveloper** [comment]
fixed this and the other two scenarios
