### ISSUE TITLE
Add Spinner - Various

### ISSUE THREAD

**Issue by sbcTestor001** [sbcDeveloper/bugs-in-time#24]
On the initial page load,  populating the name drop down list it will take a few seconds, leaving the user wondering if they will see all the names, or only the single visible name in the list.  DDL appears to be 'broken"  when clicking on it while it's still loading.  Not an issue on subsequent page loads.  Add the spinner

**Comment by sbcDeveloper** [comment]
Approval Mgmt  - On Supervisor Selection, waiting for employees to load - tab 1
Rev & Sub - GridView Pg Chg
Rev & Sub - GridView Edit and Review - Waiting on Timesheet to load
Rev and App - Gridview Edit and Review - Waiting on Timesheet to load

**Comment by sbcDeveloper** [comment]
Rev & Sub - GridView Edit and Review - Waiting on Timesheet - DONE
Rev and App - Gridview Edit and Review - Waiting on Timesheet to load - DONE
Approval Mgmt  - On Supervisor Selection, waiting for employees to load - tab 1 - DONE

**Comment by sbcDeveloper** [comment]
Rev&Sub - After Edit or Review Click - Spin Starts - then disappears while TS control loads

**Comment by sbcDeveloper** [comment]
Review&Approve/Submit & Input Leave Int - Approve/Timesheets For & Filter By BUnit - 2nd Tab  - Review or Edit
Review&Approve/Submit & Input Leave Int - Find Employee - Review or Edit
Assign Supervisors - Upon BU Chg Evt
