### ISSUE TITLE
Daily total wrong after deleting edit check error row

### ISSUE THREAD

**Issue by sbinningsbc** [sbcDeveloper/bugs-in-time#40]
![20150731_bug1](https://cloud.githubusercontent.com/assets/13142042/9013815/2a72868c-3773-11e5-9f07-4ba8a4e1bf13.png)

Then made 7/22 values 0 to test an HLB line

![20150731_bug2](https://cloud.githubusercontent.com/assets/13142042/9013824/35d2e42c-3773-11e5-80bc-982919bf895c.png)

 Did edit check 
Deleted the error HLB row. Sum on 7/22 shows -9 hours. 

![20150731_bug4](https://cloud.githubusercontent.com/assets/13142042/9013840/4cde83ba-3773-11e5-8a20-02ce486d38a6.png)

![20150731_bug5](https://cloud.githubusercontent.com/assets/13142042/9013844/55c40784-3773-11e5-9260-0099ee2ff035.png)
Change zeros back to 4.5. Sum on 7/22 is now 0. Totals for the week and pay period are correct though.
Edit check again doesn’t refresh and fix the daily total for 7/22.
![20150731_bug6](https://cloud.githubusercontent.com/assets/13142042/9013850/5dbe7a78-3773-11e5-998b-9a1232ac7b3a.png)

Approval fixes the sum on 7/22

![20150731_bug7](https://cloud.githubusercontent.com/assets/13142042/9013854/631c9c52-3773-11e5-8d7c-a147aba0c1a2.png)

**Comment by sbcDeveloper** [comment]
this bug does not require an error to be present in the row being deleted.
Reproduced the error by adding a row (to the first empty row), running editcheck, (no problems) but then deleting the row I just added.
The bug appears to be related to deletion activity performed on the first empty row, and within the same page session.  Add a row in one session.  Delete the row in another session; no bug.
Add and delete the row in the same page session will generate the calc error bug

**Comment by sbcDeveloper** [comment]
this is not specific to activity just on the first empty row.  The bug will gen when adding and deleting a row in the same page session, on any empty row

**Comment by sbcDeveloper** [comment]
calcs should update correctly independently of EditCheck, Approve or any other link button

**Comment by sbcDeveloper** [comment]
while the html footer objects were being updated for additions, the javascript global array variable totals was not, which meant when the deleted rows total(s) were removed from an inaccurate running total, the result was this bug.
