### ISSUE TITLE
Employees in roles 6-ViewBUnits, 7-ViewDepartment, and 8-ViewAll do not have access to the Reports unless they are also in one of the other special roles. Consider if all employees should go to a TimeSheet menu page with at least 2 links, one for TimeSheet and one for Reports. 

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#42]
Question: Will most employees (those not in special roles) be happier going directly into their timesheet or having the option of either going into the timesheet or printing a report?

Bug: Employees in view roles need access to Reports.

**Comment by struven** [comment]
MLS - added sp ESSPlus.HasViewOnlyAccess, DBAccess.HasViewOnlyAccess, and code in ReportsMenu.aspx

We fixed the bug, however, we still need to address the question.

**Comment by struven** [comment]
MLS - For now we will give them the option; selecting the TimeSheet tab will take all users to the TimeCapture page with the appropriate items. I'm not sure we car really do this any other way.
