### ISSUE TITLE
Review and Approve Time

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#43]
Impersonating Bob Geis.  Press Edit for Theo. Fill out Theo's  timesheet and approve. Notice that subtotals above did not refresh, so press Review for Theo. Now, totals above are refreshed but misplaced, and timesheet does not display below.

![capture](https://cloud.githubusercontent.com/assets/13423065/9065954/b84169e2-3a89-11e5-8d36-69ead1c0d801.PNG)

**Comment by sbcDeveloper** [comment]
display issue fixed by removing the timesheet id column, making room for the long timesheet status titles

**Comment by sbcDeveloper** [comment]
At this time, Earn Code / Hours table won't update for changes made in timesheet. If/When this table is moved into the timesheet, updating can be addressed then.
