### ISSUE TITLE
Leave Integration TimeSheet "templates"

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#44]
If an employee is on one of the leave integration lists, pull all of their earning codes that have hours (even SCK and VAC)  from the previous pay period forward when generating a new timesheet, not just the "productive" earnings like we do for employees not on leave.  Currently, only the productive earning codes are picked up.  
Also, along with the earning codes, pull the hours for employees on leave.

**Comment by struven** [comment]
MLS - added sql to the ESSPlus.GetTimesheet to bring in all earning codes, POPAAE, and hours from the previous payperiod for employees on leave
