### ISSUE TITLE
POPAAEE and Earning Code columns editable on locked timesheet

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#46]
Double clicking on a locked, read only timesheet in Program, OUNit, Project, Activity, Area, Equipment and Earning cells brings up a drop down which can be used to change the contents of the cell.  This also allows text to be typed in.
The changed data is not actually saved, but if possible, we should make those columns readonly and not changeable on locked timesheets.

**Comment by sbcDeveloper** [comment]
added a check to the JS function enableXXXXX
