### ISSUE TITLE
Problem with '&' in project code.

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#47]
Added hours to the first line on timesheet (2000-B&R-ADM- - EXH).  It created a new row with the same number (1), but dropped the '&R' of the project, leaving only the 'B'.  There must be a problem with the '&'??? Now there are 2 rows with Ref 1, and one has an invalid project.  Every time I add hours to the original row, they are saved on the new row.
![capture](https://cloud.githubusercontent.com/assets/13423065/9119276/a94fce72-3c2a-11e5-9a0a-8f5da8394ae2.PNG)

**Comment by sbcDeveloper** [comment]
data is passed in the url.  the data is parsed.  an "&" within the data is throwing off the parsing.  encode the data before JSON parse

**Comment by sbcDeveloper** [comment]
![2015-08-12_14-44-57](https://cloud.githubusercontent.com/assets/13138610/9237693/64d12f9e-4101-11e5-942e-fde24f69e5e4.png)
