### ISSUE TITLE
Cannot type in earning code

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#50]
I'm not sure if this was intentional, but I can no longer type in an earning code, which is much faster than adding it from the dropdown list.

**Comment by sbslatts** [comment]
POPAAE columns also no longer allow typing.

**Comment by sbcDeveloper** [comment]
pls see email dated 8/24/2015 9:35am  "Timesheets - BUG #47  Problem with '&' in project code."

**Comment by sbcDeveloper** [comment]
removed direct input block and added input validation
