### ISSUE TITLE
Cannot create pp 17 timesheet for the first time, due today

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#51]
I am impersonating Juan and trying to fill out his pp 17 timesheet for the first time (it is due today), however the dropdown does not show pay period 2015-17.  It goes right from pp 16 to pp 18.  I cannot create my timesheet.

**Comment by sbslatts** [comment]
I CAN create it as Juan's supervisor (Betsy Schaffer) in the Review and Approve screen.

**Comment by sbslatts** [comment]
Juan now has a timesheet, created by his supervisor.  To test this bug with others you can use Adriana 1203 or Rochelle 12571 or Nolan 10907.  I won't create timesheets for them until you have had a chance to debug.

**Comment by sbcDeveloper** [comment]
instead of populating the pp ddl based on the existence of a timesheet or not, the SP is based on whether the EE and job was active or not
