### ISSUE TITLE
As supervisor, can only edit (create) one time sheet for one employee without going all the way out and back in

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#52]
When I first go into Review and Approve, I see the list of my employees and I can select Edit (pencil) to create a timesheet for one of my employees.  But when I want to create another one for another employee, the Edit (pencil) icon goes away and I have to back out of the screen entirely and go back in in order to create another timesheet.
first go in:
![capture1](https://cloud.githubusercontent.com/assets/13423065/9335644/11f081a2-458a-11e5-8c2f-7a89684388b3.PNG)
As soon as the new timesheet opens up, the pencil goes away from all of the other names and even after approving the first and/or pressing the refresh, the pencils don't come back.
After:
![capture2](https://cloud.githubusercontent.com/assets/13423065/9335748/a82a968a-458a-11e5-98c8-2199d361d3ec.PNG)
Now is a good time to test this, because timesheets are due today but lots of employees (the ones I have not impersonated yet) do not have pp 17 timesheets.  As their supervisor, I want to create them today.

**Comment by sbcDeveloper** [comment]
![penciliconmissing](https://cloud.githubusercontent.com/assets/13138610/9646109/38957022-5185-11e5-806a-2aeabd6c369f.png)

**Comment by sbcDeveloper** [comment]
![bugno 58](https://cloud.githubusercontent.com/assets/13138610/9880151/4bec61f4-5b7f-11e5-9824-d20c03d07207.png)
fixed

**Comment by sbcDeveloper** [comment]
Tuesday, Sept 15th. Working on 2015-19, the pay period ended Sept 13th.  Now able to create a time sheet for an employee, and while that time sheet is still visible, select the edit icon for another employee without a time sheet and create one for that employee as well.
