### ISSUE TITLE
Add'l Row Created / Not saving earning code

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#53]
I think I might have reported this before; I am not sure.  When I add more hours to my TLC line, it creates 2 rows, one with the TLC earning code and one without.  When I add TLC into the line without the earning code, the hours are added to the TLC line with the earning code, and the earning code is not retained on the first row. In the database, there are multilpe row id 4s, one with TLC and one without.
![tlc](https://cloud.githubusercontent.com/assets/13423065/9412924/add8addc-47e3-11e5-80d2-905fbebfadc5.PNG)
![capture](https://cloud.githubusercontent.com/assets/13423065/9412971/e3c80b36-47e3-11e5-9a34-5b6f1d171f52.PNG)

**Comment by sbcDeveloper** [comment]
I'm not able to duplicate this, however I do see on hours input the totals are adjusting for TLC when they should not be - a separate BUG issue has been created for this

**Comment by sbcDeveloper** [comment]
see related bug #64
