### ISSUE TITLE
Sorting In Unexpected Pattern

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#54]
It looks like this screen is being sorted by whether or not there is a timesheet, then last name.  It should just be one list by last name, regardless of whether or not the timesheet exists.
![temp2](https://cloud.githubusercontent.com/assets/13423065/9449251/2e8fe4c6-4a56-11e5-8989-330c5690f074.PNG)

**Comment by sbslatts** [comment]
Also, I think we are going to need to be able to enter a employee id, rather than paging through to get to an employee (similar to Review and Approve screen).

**Comment by sbcDeveloper** [comment]
Payroll had asked us to sort the list first by error count
