### ISSUE TITLE
Unable to create Timesheet in Review and Approve/Submit after New Pay Period Starts a.k.a. "Missing EDIT icons"

### ISSUE THREAD

**Issue by sbcDeveloper** [sbcDeveloper/bugs-in-time#58]
As a TSA or Supervisor, unable to create a missing timesheet for an employee once the new PayPeriod starts.  Example.  Today, Tuesday Sept 1, the second day into PayPeriod 19, the supervisor is unable to create a pp 2015-18 timesheet for an employee, because the "Pencil" / edit icon is not showing.  See email from SS dated Sept 1

**Comment by sbcDeveloper** [comment]
related somewhat to closed issue:
Cannot create pp 17 timesheet for the first time, due today #51 
which is addressing the individual employee's ability to create a timesheet once the new period has started.

**Comment by sbcDeveloper** [comment]
Today, Sept 2, the  "Pencil" / edit icon is showing. App Code not modified; investigate

**Comment by sbcDeveloper** [comment]
see emails Sept 2

**Comment by sbcDeveloper** [comment]
test fix start of next PP

**Comment by struven** [comment]
MLS - This may not be a bug - I have added code to prevent this for departments not live. So this will only work in departments that are live like 061. It worked for me just now.

**Comment by sbcDeveloper** [comment]
I have it on my calendar to check/test this coming Mon-Wednesday.

**Comment by sbcDeveloper** [comment]
On QUAL, Tuesday Sept 15, the second day into PayPeriod 20, the supervisor (Theo) is able to create a pp 2015-19 timesheet for an employee, because the "Pencil" / edit icon is showing.
![bugno 58](https://cloud.githubusercontent.com/assets/13138610/9879425/2fdadaac-5b7c-11e5-8428-bd95c0029f69.png)

**Comment by sbcDeveloper** [comment]
On QUAL, no issues under Review and Submit either
