### ISSUE TITLE
Review and Submit - Remove Default Load

### ISSUE THREAD

**Issue by struven** [sbcDeveloper/bugs-in-time#60]
Here's what happens: Open Review and Submit with default PP and BUnit, change BUnit then edit runs again, change PayPeriod edit runs AND BUnit is reset to first one in the BUnit ddl (default).

Can we open Review and Submit without a BUnit and without running the edits. Then the user can select the criteria before running an edit not need to possibly run the edit twice - once on open and once with the criteria they really want to use?

**Comment by sbcDeveloper** [comment]
The grdvw should clear when user selects "Select One" in the BUnit ddl or changes the pay period
