### ISSUE TITLE
TLC hours and the daily totals

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#63]
When I entered my TLC hours for pp 19, they were added into the daily totals and they shouldn't be. Then, I went out of my time sheet and back in, and the totals were correct (not including TLC), until I changed my TLC hours.  Whatever change I made to TLC affected the daily total, making it incorrect for my "regular" hours.  This is a new bug - it was not happening last week.
![capture](https://cloud.githubusercontent.com/assets/13423065/9767725/7b1f9e00-56d4-11e5-84df-d52b2b924f8c.PNG)

**Comment by sbcDeveloper** [comment]
right O,  now that the timesheet will save POPAAEE values without hours,  and hours without POPAAEE values, including hours without an EarnCode,  add'l code work is needed to address the issue described above..  Pls see  issue "Timesheet needs to evaluate the Earncode for "TLC", "FML" and "PDL" #59"
