### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by sbslatts** [sbcDeveloper/bugs-in-time#64]
We talked about this last week, and I am not sure if you are still working on it or if you believed it to be resolved, so I will add this - please ignore if you are already working on it.
I entered hours on my HOL line which was generated when I created a brand new timesheet. I closed and went back in and now I have 2 HOL rows, one of which does not have decimals besides the hours and seems to be ingored.
![capture2](https://cloud.githubusercontent.com/assets/13423065/9767897/5b748cae-56d5-11e5-9a08-d4f26e94e7c5.PNG)

**Comment by sbcDeveloper** [comment]
a related bug is #53

**Comment by sbcDeveloper** [comment]
as with #53, I'm unable to duplicate
