### ISSUE TITLE
Clicking Refresh does not run edit checks

### ISSUE THREAD

**Issue by struven** [sbcDeveloper/bugs-in-time#66]
Review and Submit, Review and Approve: Clicking Refresh needs to run edit checks to update the errors and warnings in the gridview from the Findings table by clearing and repopulating the Findings table with the most current informatin. To verfiy this, clear the findings table and then click refresh. All errors and warnings go to 0.

**Comment by sbcDeveloper** [comment]
Performed suggested actions for  REVIEW and APPROVE - Findings table did repopulate upon REFRESH.  There is a problem however with the Warning Count being off, which is addressed under a separate BUG

**Comment by sbcDeveloper** [comment]
Performed suggested actions for REVIEW and SUBMIT- Findings table did NOT repopulate upon REFRESH.

**Comment by sbcDeveloper** [comment]
Review and Submit is different from Review and Approve in that a BUnit is in play.  A refresh on the former resets the page, which means the Findings table will not be updated until a BUnit selection is made

**Comment by struven** [comment]
I guess we need to address what we want REFRESH to do on REVIEW and SUBMIT. If it simply resets the BUnit ddl and clears the grid, then we don't need to run edits. However, I'm thinking it should be consistent with Review and Approve by running all edits and showing new counts so that the user can get the most up to date information on the Timesheets that they are responsible to submit.

**Comment by sbcDeveloper** [comment]
NOTE - On page load, Review and Approve has the advantage of already knowing the scope of the timesheets on which to run edit check, while Review and Approve has to wait for a BUnit selection.

Rev&App and Rev&Submit are both technically reloading the page.  However, as MS notes above, non-techncially, they would behave in a more similar manner if Rev&Submit does not reload the page, but instead just runs edit check (based on current BUnit selection) , clears the individual timesheet and reloads the employee grid.
