### ISSUE TITLE
Timesheet - Integrity Error numberOfRows==0

### ISSUE THREAD

**Issue by sbcDeveloper** [sbcDeveloper/bugs-in-time#7]
alert('integrity error! numberOfRows == 0'); 
For NT, 2015-15, no rows in timesheet.  See line 1862 in js file
![integrityerror](https://cloud.githubusercontent.com/assets/13138610/8530245/abddb2bc-23d4-11e5-9005-f352e8733963.jpg)

**Comment by struven** [comment]
This issue has been resolved by modifications to the sp ESSPlus.GetTimeSheet. This sp uses a prior pp timesheet has a template, however the prior timesheet had no eligible hours to use in the template, so a TimesheetID was created in Timesheets, but no rows with hours in TimesheetHours. The sp has been modifed to build a new timesheet with one empty row if no rows can be carried forward from a prior timesheet.
