### ISSUE TITLE
Review and Submit - Select Supervisor

### ISSUE THREAD

**Issue by struven** [sbcDeveloper/bugs-in-time#70]
Select a Timesheets for supervissor, then select a new payperiod. Page keeps previosly selected supervisor but there is no tab for the timesheets. The supervisor must be reselected, but you cannot reselect the same supervisor because that supervisor is selected and you cannot get the tab. Then if you select Select Supervisor so you could reset to supervisor, the app bombs. When selecting a new payperiod, the timessheets and employee ddls should be cleared as when opening the page initially.

**Comment by sbcDeveloper** [comment]
reset the select supervisor dropdownlist to index[0]
Note - a change in Pay Period resets everything

**Comment by struven** [comment]
The Review and Approve page works properly.
