### ISSUE TITLE
Reports Menu Links

### ISSUE THREAD

**Issue by struven** [sbcDeveloper/bugs-in-time#71]
When right clicking on a link to a report, the options to open in a new tab or new window are disabled. The user should be able to open in a new tab or window.

**Comment by sbcDeveloper** [comment]
![openinnewwindow](https://cloud.githubusercontent.com/assets/13138610/10142508/f5958c9c-65c7-11e5-8586-5cb1652ed5e7.png)

**Comment by sbcDeveloper** [comment]
This is because the aspx page is using the asp:LinkButton.  These options are not disabled when using asp:Hyperlink.

Check to see if any server-side processing is required before going to the target URL.  If not, change controls to hyperlink controls
