### ISSUE TITLE
Review and Submit

### ISSUE THREAD

**Issue by struven** [sbcDeveloper/bugs-in-time#74]
After selecting an employee with Find Employee, the user cannot see the whole budget unit again. Selecting Select Employee does nothing. Reseleting the same BUnit and Payperiod does nothing. Selecting Refresh clears the BUnits and Timesheet information, but then reselecting the BUnit displays only the employee previously selected but the Error and Warning counts for the whole BUnit.

**Comment by sbcDeveloper** [comment]
If one unchecks the "Find Employee" check box the complete BUnit employee grid returns
