### ISSUE TITLE
Timesheet POPAAE

### ISSUE THREAD

**Issue by struven** [sbcDeveloper/bugs-in-time#75]
When selecting POPAAE from the dropdown the user cannot reselect the same POPAAE as in the cell. Once the ddl is activated the user must make a different selection to complete data entry in the cell. The user can exit the cell with Tab, but the ddl remains.

**Comment by sbcDeveloper** [comment]
Need to be able to select the same POPAAEE code upon which ddl should close
Need to close ddl upon keyboard tab event
No more than one open ddl at a time

**Comment by sbcDeveloper** [comment]
fixed with mouseout event
